service: github-authentication

provider:
  name: aws
  environment:
    CLIENT_ID: ${file(./serverless.env.yml):dev.CLIENT_ID}
    CLIENT_SECRET: ${file(./serverless.env.yml):dev.CLIENT_SECRET}
  runtime: nodejs6.10

package:
  exclude:
    - .git/**

functions:
  callback:
    handler: handler.callback
    environment:
      URL: https://github.com/login/oauth/access_token
    memorySize: 256
    timeout: 15
    events:
      - http:
          path: callback
          method: get
          integration: lambda-proxy