service: get-s3-buckets

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  getBuckets:
    handler: handler.endpoint
    events:
      - http:
          path: buckets
          method: get
